// Do not alter this file, instead it should be generated by using `yarn svg`
// This will override this file and update the exported enum for use in the SvgIcon component

export enum TLASvg {
    arc3d = 'arc3d',
    close24 = 'close24',
}