// Do not alter this file, instead it should be generated by using `yarn svg`
// This will override this file and update the exported map for use in the SvgIcon component

import { FC } from 'react';
import Arc3d from './arc3d.svg';
import Close from './close.svg';

export const TLAIcons: { [key: string]: FC<any> } = {
    arc3d: Arc3d,
    close: Close,
}